### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by alisyd** [srowley/ggity#36]
I know I shouldn't ask this here, but is there a way to display tooltips on shapes, and data points, when you hover on to a shape or a point, it should display the value at that point, how do I achieve this using this library. Thanks for any help.

**Comment by srowley** [comment]
Cool question!

I would use two layers, one for the shape and one for the text of the value. Then manipulate the visibility of items in the text layer using JavaScript and custom attributes. 

Here is an example; with better knowledge of CSS and JavaScript I'm sure it can be improved. For instance this technically shows the tooltip when you mouse over the text, not the shape (it just happens to position the text on top of the shape). 

There might also be more efficient/otherwise better ways to do this if you add an external stylesheet with classes that can get toggled in the custom attributes.

```elixir
    Examples.mtcars()
      |> Plot.new(%{x: :wt, y: :mpg, label: :model})
      |> Plot.geom_text(custom_attributes: fn _plot, _row ->
          [
            pointer_events: "all",
            visibility: "hidden",
            onmouseover: "evt.target.setAttribute('visibility', 'visible');",
            onmouseout: "evt.target.setAttribute('visibility', 'hidden');"
          ]
        end)
      |> Plot.geom_point(%{x: :wt, y: :mpg})
      |> Plot.plot()
```
